INCLUDES = -I/usr/X11R6/include -I/usr/local/include
LIBS = -lX11 -lXext -ltcl8.4
LIBPATH =  -L/usr/local/lib -L/usr/X11R6/lib -L/usr/lib
SHLIB_CFLAGS = -fPIC -O -g
SHLIB_LD = ld -G -z text
DIR=../../shape
CFLAGS+=$(CXFLAGS) -DSTATIC_BUILD=1 -g


shaped.so: shaped.c
	$(CC) -c ${SHLIB_CFLAGS} shaped.c
	${SHLIB_LD}  $(LIBPATH) $(LIBS) -o shaped.so shaped.o

libshaped.a:
	$(CC) -c $(CFLAGS) shaped.c
	${AR}  rv libshaped.a shaped.o

